Repository kleveross/ormb, pull requests merged in 2020-07, with the labels that each got.

#79 fix(link): error link
  README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#81 chore: Disable CGO by default
  .goreleaser.yml
  Makefile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#83 feat(initializer): Use subcommand to keep the real logic
  build/ormb-storage-initializer/Dockerfile
  cmd/ormb-storage-initializer/cmd/pull-and-export.go
  cmd/ormb-storage-initializer/cmd/root.go
  docs/tutorial-serving-seldon.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#84 feat(makefile): Enable CGO
  .goreleaser.yml
  Makefile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#85 feat: Add CLI demo in readme
  README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#86 fix(Makefile): enable race detection in tests only
  Makefile
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#87 chore: Revise README and remove cgo in goreleaser
  .goreleaser.yml
  README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#88 chore: Update owners
  OWNERS
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#98 feat: Support loglevel
  cmd/ormb/cmd/prerun.go
  cmd/ormb/cmd/root.go
Labels: approved, lgtm, release-note-none, size/M

#99 feat: Implement tag subcommand
  cmd/ormb/cmd/tag.go
  pkg/oras/cache/cache.go
  pkg/oras/cache/cache_test.go
  pkg/oras/cache/interface.go
  pkg/oras/cache/mock/mock.go
  pkg/oras/client.go
  pkg/oras/client_test.go
  pkg/oras/interface.go
  pkg/oras/mock/mock.go
  pkg/ormb/ormb.go
Labels: approved, lgtm, release-note-none, size/L

#100 fix(oci): Suppport ip for cmd
  pkg/oci/reference.go
Labels: approved, lgtm, release-note-none, size/XS
