Repository kleveross/ormb, pull requests merged in 2020-10, with the labels that each got.

#140 feat(MLflow)[KLV-30]: Support mlflow
  examples/MLflow-model/model/MLmodel
  examples/MLflow-model/model/conda.yaml
  examples/MLflow-model/model/model.pkl
  examples/MLflow-model/ormbfile.yaml
  pkg/model/format.go
  pkg/model/format_test.go
  test/Corrupt/model/corrupt
  test/Corrupt/ormbfile.yaml
Labels: approved, kind/feature, lgtm, release-note-none, size/M

#141 feat(KLV-30): add relayout function for MLflow
  cmd/ormb-storage-initializer/cmd/pull-and-export.go
Labels: approved, lgtm, release-note, size/M

#142 feat(KLV-30): remove the opaque environment of AWS
  cmd/ormb-storage-initializer/cmd/pull-and-export.go
Labels: approved, lgtm, release-note-none, size/XS

#143 Feat(examples): add spark mllib model example
  examples/MLlib-model/model/data/.part-00000-3b569ac9-e283-4220-ba6c-31088ed23cb8-c000.snappy.parquet.crc
  examples/MLlib-model/model/data/_SUCCESS
  examples/MLlib-model/model/data/part-00000-3b569ac9-e283-4220-ba6c-31088ed23cb8-c000.snappy.parquet
  examples/MLlib-model/model/metadata/.part-00000.crc
  examples/MLlib-model/model/metadata/_SUCCESS
  examples/MLlib-model/model/metadata/part-00000
  examples/MLlib-model/ormbfile.yaml
Labels: approved, lgtm, release-note-none, size/XS

#144 docs: update for a better env name
  docs/tutorial-serving-seldon.md
Labels: approved, lgtm, release-note-none, size/S
