Repository kleveross/ormb, pull requests merged in 2020-06, with the labels that each got.

#21 fix(cmd): Remove panic logic
  cmd/ormb/cmd/export.go
  cmd/ormb/cmd/login.go
  cmd/ormb/cmd/pull.go
  cmd/ormb/cmd/push.go
  cmd/ormb/cmd/save.go
  pkg/ormb/ormb.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#22 feat(cmd): Support remove cmd
  .gitignore
  cmd/ormb/cmd/remove.go
  pkg/oci/client.go
  pkg/ormb/ormb.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#26 feat: Print format in stdout
  README.md
  examples/SavedModel-fashion/ormbfile.yaml
  pkg/model/types.go
  pkg/oci/client.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#28 feat: Export metadata
  examples/SavedModel-fashion/training-serving.ipynb
  pkg/exporter/exporter.go
  pkg/model/types.go
  pkg/oci/cache.go
  pkg/ormb/ormb.go
  pkg/parser/parser.go
  pkg/saver/saver.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#30 feat: Add goreleaser config yaml
  .gitignore
  .goreleaser.yml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#31 feat: update OWNERS
  OWNERS
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#35 feat: Implement storage initializer for Seldon and KF
  .dockerignore
  .goreleaser.yml
  Makefile
  build/admin/Dockerfile
  build/controller/Dockerfile
  build/ormb-storage-initializer/Dockerfile
  build/ormb/Dockerfile
  cmd/ormb-storage-initializer/cmd/option.go
  cmd/ormb-storage-initializer/cmd/prerun.go
  cmd/ormb-storage-initializer/cmd/root.go
  cmd/ormb-storage-initializer/main.go
  docs/images/harbor-projects.png
  docs/images/harbor-registration.png
  docs/images/harbor-tf.png
  docs/tutorial-serving-seldon.md
  pkg/oci/client.go
  vendor/github.com/Microsoft/hcsshim/mksyscall_windows.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/modules.txt
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL

#45 support python sdk for ormb
  .gitignore
  extern-sdk/python/README.md
  extern-sdk/python/git_release.py
  extern-sdk/python/ormb/__init__.py
  extern-sdk/python/ormb/api.py
  extern-sdk/python/requirements.txt
  extern-sdk/python/setup.py
  extern-sdk/python/tests/__init__.py
  extern-sdk/python/tests/test_main.py
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#52 feat: Release python package in pypi
  extern-sdk/python/.gitignore
  extern-sdk/python/OWNERS
  extern-sdk/python/setup.py
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#51 feat: Update readme
  README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#56 feat: Use docker.io in Makefile
  Makefile
  README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#58 feat: Support signature in metadata data structure
  pkg/model/types.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#60 feat(ci): Add Travis CI config
  .travis.yaml
  README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#64 feat: Add test for oras client
  .travis.yml
  Makefile
  cmd/ormb-storage-initializer/cmd/prerun.go
  cmd/ormb-storage-initializer/cmd/root.go
  cmd/ormb/cmd/prerun.go
  pkg/oci/interface.go
  pkg/oci/util.go
  pkg/oras/auth.go
  pkg/oras/cache/cache.go
  pkg/oras/cache/cache_opts.go
  pkg/oras/cache/interface.go
  pkg/oras/cache/mock/mock.go
  pkg/oras/client.go
  pkg/oras/client_opts.go
  pkg/oras/client_test.go
  pkg/oras/interface.go
  pkg/oras/mock/mock.go
  pkg/oras/mock/mock_auth.go
  pkg/oras/mock/mock_resolver.go
  pkg/oras/oras_suite_test.go
  pkg/oras/orasclient/interface.go
  pkg/oras/orasclient/mock/mock.go
  pkg/oras/orasclient/oras.go
  pkg/oras/resolver.go
  pkg/ormb/ormb.go
  pkg/ormb/ormb_test.go
  pkg/util/bytes/byte.go
  pkg/util/ctx/ctx.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XL

#65 chore(ci): Add coveralls
  .travis.yml
  README.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#66 feat: Add client test
  pkg/oras/client.go
  pkg/oras/client_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#67 fix(example): Update savedmodel example
  examples/SavedModel-fashion/model/saved_model.pb
  examples/SavedModel-fashion/model/variables/variables.data-00000-of-00001
  examples/SavedModel-fashion/model/variables/variables.index
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#68 feat: Add test for cache
  .gitignore
  pkg/oras/cache/cache_suite_test.go
  pkg/oras/cache/cache_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#72 feat(pmml): Support PMML signature
  pkg/model/types.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#71 feat: Add version subcommand
  Makefile
  cmd/ormb-storage-initializer/cmd/version.go
  cmd/ormb/cmd/version.go
  pkg/version/version.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#74 feat: Update spec's Tensor
  docs/spec-v1alpha1.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS

#70 feat: Add more tests
  .travis.yml
  pkg/exporter/exporter_suite_test.go
  pkg/exporter/exporter_test.go
  pkg/saver/saver_suite_test.go
  pkg/saver/saver_test.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M

#75 feat: Add logo
  README.md
  docs/images/logo.png
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#78 feat: Remove useless logic
  cmd/ormb-storage-initializer/cmd/root.go
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/M
