Repository kleveross/ormb, pull requests merged in 2020-09, with the labels that each got.

#123 chore(docs): add chinese version of README
  README.md
  README_zh.md
Labels: approved, lgtm, release-note-none, size/M

#124 fix: Fix the goreleaser and vendor
  .goreleaser.yml
  OWNERS
  go.mod
  go.sum
  vendor/golang.org/x/sync/semaphore/semaphore.go
  vendor/modules.txt
Labels: approved, lgtm, release-note-none, size/S

#125 chore(docs): add ormb doc and open source license
  CONTRIBUTING.md
  LICENSE
  README.md
  README_zh.md
  docs/README.md
  docs/docs_zh/README.md
  docs/docs_zh/introduction.md
  docs/introduction.md
Labels: approved, lgtm, release-note-none, size/XXL

#126 fix(ci): add github actions
  .github/workflow/main.yml
Labels: approved, lgtm, release-note-none, size/M

#127 fix: Fix dir name to workflows
  .github/workflows/main.yml
Labels: approved, lgtm, release-note-none, size/XS

#129 fix(ci): fix github action ci
  .github/workflows/main.yml
  Makefile
Labels: approved, lgtm, release-note-none, size/S

#128 chore(docs): add CONTRIBUTING doc
  CONTRIBUTING.md
Labels: approved, lgtm, release-note-none, size/M

#130 Feat(models): add sklearn and xgboost model examples
  examples/SKLearn-model/model/model.joblib
  examples/SKLearn-model/ormbfile.yaml
  examples/XGBoost-model/model/model.json
  examples/XGBoost-model/ormbfile.yaml
Labels: approved, lgtm, release-note-none, size/XS

#131 Feat(format): add sklearn and xgboost model format validate
  examples/XGBoost-model/model/model.xgboost
  pkg/model/format.go
  pkg/model/format_test.go
Labels: approved, lgtm, release-note-none, size/M

#133 feat: Add coverage
  .github/workflows/main.yml
Labels: approved, lgtm, release-note-none, size/XS

#134 chore(makefile): Update makefile
  Makefile
Labels: approved, lgtm, release-note-none, size/XS

#135 feat(action): Add publish action
  .github/workflows/publish.yml
Labels: approved, lgtm, release-note-none, size/M

#136 fix: Fix publish action version
  .github/workflows/main.yml
  .github/workflows/publish.yml
Labels: release-note-none, size/S
