Repository kleveross/ormb, pull requests merged in 2020-11, with the labels that each got.

#145 feat: compatible with two levels for model ref
  cmd/ormb/cmd/prerun.go
  cmd/ormb/cmd/util.go
  cmd/ormb/cmd/util_test.go
Labels: approved, lgtm, release-note, size/M

#147 feat: mkdir target directory if it doesn't exist on exporting
  pkg/ormb/ormb.go
Labels: approved, lgtm, release-note-none, size/XS

#148 chore(*): update github action
  .github/workflows/main.yml
  .github/workflows/publish.yml
  pkg/ormb/ormb_test.go
Labels: approved, lgtm, release-note-none, size/S

#152 chore(*): update github template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm
