Repository kleveross/ormb, pull requests merged in 2020-12, with the labels that each got.

#153 feat(cmd): support plainHTTP opt for Pull&Push func
  cmd/ormb-storage-initializer/cmd/pull-and-export.go
  cmd/ormb/cmd/pull.go
  cmd/ormb/cmd/push.go
  pkg/oras/client.go
  pkg/oras/interface.go
  pkg/ormb/ormb.go
Labels: approved, area/model, kind/feature, lgtm, release-note, size/S

#155 fix(*): revert last two commit
  cmd/ormb-storage-initializer/cmd/pull-and-export.go
  cmd/ormb/cmd/pull.go
  cmd/ormb/cmd/push.go
  pkg/oras/client.go
  pkg/oras/interface.go
  pkg/oras/mock/mock.go
  pkg/ormb/mock/mock.go
  pkg/ormb/ormb.go
  pkg/ormb/ormb_test.go
Labels: approved, kind/regression, lgtm, release-note, size/M

#156 fix(examples): fix graphdef example
  examples/GraphDef-model/ormbfile.yaml
Labels: approved, area/model, kind/bug, lgtm, release-note, size/S

#157 feat(makefile): generate mock auto
  Makefile
  pkg/ormb/mock/mock.go
  pkg/ormb/mock/mock_ormb.go
Labels: approved, kind/feature, lgtm, release-note, size/L

#159 feat(check): skip Others format validate
  pkg/model/format.go
  pkg/model/format_test.go
Labels: approved, kind/bug, lgtm, release-note, size/XS

#161 feat(ormb): update ormb Metrics
  docs/docs_zh/introduction.md
  docs/introduction.md
  docs/spec-v1alpha1.md
  pkg/model/types.go
Labels: approved, area/model, kind/feature, lgtm, release-note, size/M

#162 fix(type): MetricList type error
  pkg/model/types.go
Labels: approved, kind/bug, lgtm, release-note-none, size/XS

#165 Fix(docs): fix broken link in doc and format doc
  docs/docs_zh/introduction.md
  docs/introduction.md
Labels: approved, area/serving, kind/documentation, lgtm, release-note, size/L

#166 fix(format): remove check variables dir for savedmodel
  pkg/model/format.go
Labels: approved, kind/bug, lgtm, release-note, size/XS
