Repository kleveross/ormb, pull requests merged in 2020-08, with the labels that each got.

#105 feat: Support TLS verification skip flag
  cmd/ormb-storage-initializer/cmd/prerun.go
  cmd/ormb-storage-initializer/cmd/pull-and-export.go
  cmd/ormb/cmd/login.go
  cmd/ormb/cmd/prerun.go
  cmd/ormb/cmd/pull.go
  cmd/ormb/cmd/push.go
  go.mod
  go.sum
  pkg/oras/client.go
  pkg/oras/client_opts.go
  vendor/modules.txt
Labels: approved, lgtm, release-note-none, size/S

#104 feat(goreleaser): Add release version info for goreleaser
  .goreleaser.yml
  Makefile
  cmd/ormb-storage-initializer/main.go
  cmd/ormb/main.go
Labels: approved, lgtm, release-note-none, size/S

#109 feat(makefile): Update clever to klever
  Makefile
Labels: approved, lgtm

#110 feat(ormb-storage-initializer): Relayout model file for serving
  cmd/ormb-storage-initializer/cmd/option.go
  cmd/ormb-storage-initializer/cmd/prerun.go
  cmd/ormb-storage-initializer/cmd/pull-and-export.go
Labels: approved, lgtm, release-note-none, size/M

#112 chore: move validation to default branch
  pkg/oci/reference.go
  pkg/oras/cache/cache.go
Labels: approved, lgtm, release-note-none, size/XS

#113 chore: add default tag when tag is empty
  pkg/oci/reference.go
  pkg/oras/client.go
Labels: approved, lgtm, release-note-none, size/S

#114 feat: Update TorchScript and NetDef example model
  examples/Caffe2-model/ormbfile.yaml
  examples/TorchScript-model/ormbfile.yaml
Labels: approved, lgtm, release-note-none, size/M

#107 feat: Add GPUType field for TensorRT
  pkg/model/types.go
Labels: approved, lgtm, release-note-none, size/XS

#117 feat: Add more metadata for GraphDef example
  examples/GraphDef-model/ormbfile.yaml
Labels: approved, lgtm, release-note-none, size/M

#121 feat(metadata): Support directory structure
  pkg/model/types.go
  pkg/saver/saver.go
Labels: approved, lgtm, release-note-none, size/M
