Repository kleveross/ormb, pull requests merged in 2021-01, with the labels that each got.

#170 feat(model): generate ormbfile.yaml automatically
  pkg/saver/saver.go
  pkg/util/util.go
  pkg/util/util_test.go
Labels: approved, area/model, kind/feature, lgtm, release-note-none, size/L

#171 fix(config): fix rootPath env
  cmd/ormb/cmd/root.go
Labels: approved, kind/bug, lgtm, release-note-none, size/XS

#172 feat(cmd): impl ormb models command
  cmd/ormb/cmd/model.go
  go.mod
  go.sum
  pkg/oras/client.go
  pkg/oras/interface.go
  pkg/oras/mock/mock.go
  pkg/ormb/mock/mock_ormb.go
  pkg/ormb/ormb.go
  pkg/util/bytes/byte.go
  vendor/github.com/xeonx/timeago/.travis.yml
  vendor/github.com/xeonx/timeago/LICENSE
  vendor/github.com/xeonx/timeago/README.md
  vendor/github.com/xeonx/timeago/timeago.go
  vendor/modules.txt
Labels: approved, kind/feature, lgtm, release-note, size/L

#174 Fix(docs): fix ormb save command in doc
  README.md
  README_zh.md
  docs/README.md
  docs/docs_zh/README.md
  docs/introduction.md
Labels: approved, kind/bug, lgtm, release-note, size/S
